import { RegisterStepsProvider } from "@/contexts/RegisterStepsContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CV Upload",
  description: "Generated by Massar Graduation App Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RegisterStepsProvider>
      <div className="flex items-center min-h-screen">{children}</div>
    </RegisterStepsProvider>
  );
}
