import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "../styles/globals.css";
import { ToastContainer } from 'react-toastify';
import { Analytics } from '@vercel/analytics/next';


const BaseFont= Roboto_Slab({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BaseFont.className}`}
      >
        <ToastContainer position="top-center" />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
